[package]
name = "signals-and-slots"
version = "0.0.0"
authors = ["Fred Mitchell <fred.mitchell@gmx.de>"]
edition = "2018"
license = "MIT"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
ident = "0.3.10"
crossbeam = "0.7.3"
